/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as AppliedRouteImport } from './routes/applied'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AdminSupportRouteImport } from './routes/admin-support'
import { Route as AdminStripeConfigRouteImport } from './routes/admin-stripe-config'
import { Route as AdminPlanConfigRouteImport } from './routes/admin-plan-config'
import { Route as AdminFlagsRouteImport } from './routes/admin-flags'
import { Route as AdminDocsRouteImport } from './routes/admin-docs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin-announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesCompanyAppliedRouteImport } from './routes/companies.$company.applied'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedRoute = AppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin-support',
  path: '/admin-support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStripeConfigRoute = AdminStripeConfigRouteImport.update({
  id: '/admin-stripe-config',
  path: '/admin-stripe-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanConfigRoute = AdminPlanConfigRouteImport.update({
  id: '/admin-plan-config',
  path: '/admin-plan-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/admin-flags',
  path: '/admin-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/admin-docs',
  path: '/admin-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin-announcements',
  path: '/admin-announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyAppliedRoute = CompaniesCompanyAppliedRouteImport.update({
  id: '/companies/$company/applied',
  path: '/companies/$company/applied',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-docs': typeof AdminDocsRoute
  '/admin-flags': typeof AdminFlagsRoute
  '/admin-plan-config': typeof AdminPlanConfigRoute
  '/admin-stripe-config': typeof AdminStripeConfigRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-users': typeof AdminUsersRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/companies/$company/applied': typeof CompaniesCompanyAppliedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-docs': typeof AdminDocsRoute
  '/admin-flags': typeof AdminFlagsRoute
  '/admin-plan-config': typeof AdminPlanConfigRoute
  '/admin-stripe-config': typeof AdminStripeConfigRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-users': typeof AdminUsersRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/companies/$company/applied': typeof CompaniesCompanyAppliedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-docs': typeof AdminDocsRoute
  '/admin-flags': typeof AdminFlagsRoute
  '/admin-plan-config': typeof AdminPlanConfigRoute
  '/admin-stripe-config': typeof AdminStripeConfigRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-users': typeof AdminUsersRoute
  '/applied': typeof AppliedRoute
  '/configuration': typeof ConfigurationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/companies/$company/applied': typeof CompaniesCompanyAppliedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/admin-announcements'
    | '/admin-docs'
    | '/admin-flags'
    | '/admin-plan-config'
    | '/admin-stripe-config'
    | '/admin-support'
    | '/admin-users'
    | '/applied'
    | '/configuration'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/companies/$company/applied'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/admin-announcements'
    | '/admin-docs'
    | '/admin-flags'
    | '/admin-plan-config'
    | '/admin-stripe-config'
    | '/admin-support'
    | '/admin-users'
    | '/applied'
    | '/configuration'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/companies/$company/applied'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-analytics'
    | '/admin-announcements'
    | '/admin-docs'
    | '/admin-flags'
    | '/admin-plan-config'
    | '/admin-stripe-config'
    | '/admin-support'
    | '/admin-users'
    | '/applied'
    | '/configuration'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/support'
    | '/verify-email'
    | '/companies/$company/applied'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminPlanConfigRoute: typeof AdminPlanConfigRoute
  AdminStripeConfigRoute: typeof AdminStripeConfigRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppliedRoute: typeof AppliedRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CompaniesCompanyAppliedRoute: typeof CompaniesCompanyAppliedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied': {
      id: '/applied'
      path: '/applied'
      fullPath: '/applied'
      preLoaderRoute: typeof AppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-support': {
      id: '/admin-support'
      path: '/admin-support'
      fullPath: '/admin-support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-stripe-config': {
      id: '/admin-stripe-config'
      path: '/admin-stripe-config'
      fullPath: '/admin-stripe-config'
      preLoaderRoute: typeof AdminStripeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-plan-config': {
      id: '/admin-plan-config'
      path: '/admin-plan-config'
      fullPath: '/admin-plan-config'
      preLoaderRoute: typeof AdminPlanConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-flags': {
      id: '/admin-flags'
      path: '/admin-flags'
      fullPath: '/admin-flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-docs': {
      id: '/admin-docs'
      path: '/admin-docs'
      fullPath: '/admin-docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-announcements': {
      id: '/admin-announcements'
      path: '/admin-announcements'
      fullPath: '/admin-announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$company/applied': {
      id: '/companies/$company/applied'
      path: '/companies/$company/applied'
      fullPath: '/companies/$company/applied'
      preLoaderRoute: typeof CompaniesCompanyAppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminPlanConfigRoute: AdminPlanConfigRoute,
  AdminStripeConfigRoute: AdminStripeConfigRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppliedRoute: AppliedRoute,
  ConfigurationRoute: ConfigurationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CompaniesCompanyAppliedRoute: CompaniesCompanyAppliedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
