import type { AppliedJobStatus, InterviewOutcome } from "./types";

export const CONFIG_KEY = "runtime:config";
export const INVENTORY_KEY = "runtime:latest_inventory";
export const TREND_KEY = "runtime:trend_points";
export const APPLIED_KEY = "runtime:applied_jobs";
export const JOB_NOTES_KEY = "runtime:job_notes";
export const JOB_NOTE_RECORDS_KEY = "runtime:job_note_records";
export const LAST_NEW_JOBS_COUNT_KEY = "runtime:last_new_jobs_count";
export const LAST_NEW_JOB_KEYS_KEY = "runtime:last_new_job_keys";
export const LAST_UPDATED_JOBS_COUNT_KEY = "runtime:last_updated_jobs_count";
export const LAST_UPDATED_JOB_KEYS_KEY = "runtime:last_updated_job_keys";
export const SAVED_FILTERS_KEY = "runtime:saved_filters";
export const DISCARDED_JOB_KEYS_KEY = "runtime:discarded_job_keys";
export const ACTIVE_RUN_LOCK_KEY = "runtime:active_run_lock";
export const COMPANY_SCAN_OVERRIDES_KEY = "runtime:company_scan_overrides";
export const EMAIL_WEBHOOK_CONFIG_KEY = "email-webhook-config";
export const EMAIL_ATTEMPT_PREFIX = "runtime:email-attempt:";

export const ATS_CACHE_PREFIX = "ats:";
export const SEEN_PREFIX = "seen:";
export const FIRST_SEEN_PREFIX = "firstseen:";
export const PROTECTED_DISCOVERY_PREFIX = "protected:ats-discovery:";
export const APP_LOG_PREFIX = "runtime:applog:";
export const DECISION_SUMMARY_PREFIX = "runtime:decision-summary:";

export const ATS_CACHE_TTL_SECONDS = 60 * 60 * 24 * 7;
export const SMARTRECRUITERS_PAGE_SIZE = 100;
export const WORKDAY_PAGE_SIZE = 20;
export const TREND_RETENTION_POINTS = 180;
export const APP_LOG_TTL_SECONDS = 60 * 60 * 6;
export const DECISION_SUMMARY_TTL_SECONDS = 60 * 60 * 6;
export const ACTIVE_RUN_LOCK_TTL_SECONDS = 60 * 30;
export const ACTIVE_RUN_STALE_AFTER_SECONDS = 60 * 4;
export const DEFAULT_APP_LOG_LIMIT = 200;
export const MAX_APP_LOG_LIMIT = 1000;

export const VALID_STATUSES: AppliedJobStatus[] = ["Applied", "Interview", "Negotiations", "Offered", "Rejected"];
export const VALID_INTERVIEW_OUTCOMES: InterviewOutcome[] = ["Pending", "Passed", "Failed", "Follow-up"];

export const US_STATE_CODES = new Set([
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA",
  "MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN",
  "TX","UT","VT","VA","WA","WV","WI","WY","DC"
]);

export const NON_US_HINTS = [
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "aruba",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "brunei darussalam",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cape verde",
  "cambodia",
  "cameroon",
  "canada",
  "cayman islands",
  "central african republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "columbia",
  "comoros",
  "congo",
  "republic of the congo",
  "democratic republic of the congo",
  "costa rica",
  "cote d ivoire",
  "cote d'ivoire",
  "ivory coast",
  "croatia",
  "cuba",
  "curacao",
  "curaçao",
  "cyprus",
  "czech republic",
  "czechia",
  "denmark",
  "djibouti",
  "dominica",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "swaziland",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "greenland",
  "grenada",
  "guatemala",
  "guinea",
  "guinea bissau",
  "guyana",
  "haiti",
  "honduras",
  "hong kong",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "isle of man",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jersey",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kosovo",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "lao pdr",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "macao",
  "macau",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall islands",
  "martinique",
  "mauritania",
  "mauritius",
  "mexico",
  "micronesia",
  "federated states of micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar",
  "burma",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new caledonia",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north macedonia",
  "macedonia",
  "northern mariana islands",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "palestine",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "puerto rico",
  "qatar",
  "romania",
  "russia",
  "russian federation",
  "rwanda",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and the grenadines",
  "samoa",
  "san marino",
  "sao tome and principe",
  "saudi arabia",
  "scotland",
  "senegal",
  "serbia",
  "seychelles",
  "sierra leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon islands",
  "somalia",
  "south africa",
  "south korea",
  "korea",
  "south sudan",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "taiwan",
  "tajikistan",
  "tanzania",
  "thailand",
  "timor leste",
  "east timor",
  "togo",
  "tonga",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "turks and caicos",
  "tuvalu",
  "uganda",
  "uk",
  "ukraine",
  "united arab emirates",
  "uae",
  "united kingdom",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican city",
  "venezuela",
  "vietnam",
  "virgin islands",
  "british virgin islands",
  "u s virgin islands",
  "wales",
  "yemen",
  "zambia",
  "zimbabwe",
  "mexico city",
  "emirates",
  "taipei",
  "prague",
  "bucharest",
  "warsaw",
  "krakow",
  "wroclaw",
  "amsterdam",
  "rotterdam",
  "berlin",
  "munich",
  "hamburg",
  "paris",
  "barcelona",
  "madrid",
  "lisbon",
  "zurich",
  "geneva",
  "toronto",
  "vancouver",
  "montreal",
  "mississauga",
  "ottawa",
  "bogota",
  "medellin",
  "buenos aires",
  "sao paulo",
  "rio de janeiro",
  "sydney",
  "melbourne",
  "brisbane",
  "auckland",
  "seoul",
  "tokyo",
  "osaka",
  "beijing",
  "shanghai",
  "shenzhen",
  "manila",
  "jakarta",
  "kuala lumpur",
  "bangkok",
  "noida",
  "gurugram",
  "pune",
  "bangalore",
  "banglore",
  "bengaluru",
  "mumbai",
  "hyderabad",
  "chennai",
  "delhi",
  "new delhi",
  "kolkata",
  "yokneam",
  "rawabi",
  "london",
  "dublin",
  "belfast",
  "edinburgh",
  "bern",
  "frankfurt",
  "glattbrugg"
];

export const NON_US_TITLE_HINTS = [
  "emea",
  "europe",
  "european union",
  "german speaking",
];
